spring.application.name=BookStore
# Sunucu Portu
server.port=1001


# PostgreSQL Veritaban? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA ve Hibernate Ayarlar?
# ddl-auto: Veritaban? ?emas?n? otomatik yönetir (update, create, create-drop, validate, none)
spring.jpa.hibernate.ddl-auto=update

# Hibernate Dialect: PostgreSQL'e özel SQL üretimi için
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL sorgular?n? konsola yazd?rmak için (iste?e ba?l?)
spring.jpa.show-sql=true